import { MockupV2Template } from './types';

export const mockupV2Templates: Record<string, MockupV2Template> = {
  // ─── Apparel ───
  'onesie': {
    id: 'onesie',
    name: 'Baby Onesie',
    description: 'See your pattern on a baby onesie',
    category: 'apparel',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 10.5, height: 18, unit: 'in' },
    sizeLabel: '10.5×18" (26.7×45.7cm) Baby Onesie',
    productBase: { type: 'image', imagePath: '/mockups/onesie.png', maskPath: '/mockups/onesie_mask_new.png' },
    colorOverlay: { maskPath: '/mockups/onesie_mask_color.png', defaultColor: 'auto' },
  },
  'girl-dress-1': {
    id: 'girl-dress-1',
    name: "Girls' Dress",
    description: 'Photo-based girls dress with bodice, sleeves, and skirt zones',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 472, y: 934, width: 2020, height: 3219 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'bodice',
        maskPath: '/mockups/v2/girl-dress-1-bodice-mask.png',
        patternArea: { x: 772, y: 934, width: 1445, height: 1848 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 12,
      },
      {
        id: 'sleeves',
        maskPath: '/mockups/v2/girl-dress-1-sleeves-mask.png',
        patternArea: { x: 573, y: 1031, width: 1879, height: 687 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
      },
      {
        id: 'skirt',
        maskPath: '/mockups/v2/girl-dress-1-skirt-mask.png',
        patternArea: { x: 472, y: 2726, width: 2020, height: 1427 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 26, unit: 'in' },
    sizeLabel: "22×26\" (55.9×66cm) Girls' Dress",
    productBase: { type: 'image', imagePath: '/mockups/v2/girl-dress-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/girl-dress-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/girl-dress-1-shadow.png',
    highlightPath: '/mockups/v2/girl-dress-1-highlight.png',
  },
  'swim-trunks-1': {
    id: 'swim-trunks-1',
    name: "Men's Swim Trunks",
    description: 'Swim trunks with a contrast hem panel',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 106, y: 1138, width: 2672, height: 2331 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/swim-trunks-1-mask.png',
        patternArea: { x: 111, y: 1138, width: 2667, height: 2226 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
      },
      {
        id: 'hem',
        maskPath: '/mockups/v2/swim-trunks-1-hem-mask.png',
        patternArea: { x: 106, y: 2717, width: 2660, height: 752 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 19, unit: 'in' },
    sizeLabel: "22×19\" (55.9×48.3cm) Men's Swim Trunks",
    productBase: { type: 'image', imagePath: '/mockups/v2/swim-trunks-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/swim-trunks-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/swim-trunks-1-shadow.png',
    highlightPath: '/mockups/v2/swim-trunks-1-highlight.png',
  },
  'swimsuit-kids-2': {
    id: 'swimsuit-kids-2',
    name: "Kids' One-Piece Swimsuit",
    description: 'One-piece swimsuit for kids',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 525, y: 610, width: 1868, height: 3272 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 12, height: 22, unit: 'in' },
    sizeLabel: "12×22\" (30.5×55.9cm) Kids' Swimsuit",
    productBase: { type: 'image', imagePath: '/mockups/v2/swimsuit-kids-2.png', maskPath: '/mockups/v2/swimsuit-kids-2-mask.png' },
    colorOverlay: { maskPath: '/mockups/v2/swimsuit-kids-2-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/swimsuit-kids-2-shadow.png',
    highlightPath: '/mockups/v2/swimsuit-kids-2-highlight.png',
  },
  'girl-dress-2': {
    id: 'girl-dress-2',
    name: "Girls' Tiered Dress",
    description: 'Tiered girls dress with bodice and three ruffle panels',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 514, y: 905, width: 1866, height: 2217 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'bodice',
        maskPath: '/mockups/v2/girl-dress-2-bodice-mask.png',
        patternArea: { x: 1237, y: 905, width: 606, height: 744 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 9,
      },
      {
        id: 'top',
        maskPath: '/mockups/v2/girl-dress-2-top-mask.png',
        patternArea: { x: 1038, y: 1562, width: 966, height: 608 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 14,
      },
      {
        id: 'middle',
        maskPath: '/mockups/v2/girl-dress-2-middle-mask.png',
        patternArea: { x: 880, y: 2063, width: 1284, height: 466 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
      },
      {
        id: 'bottom',
        maskPath: '/mockups/v2/girl-dress-2-bottom-mask.png',
        patternArea: { x: 514, y: 2374, width: 1866, height: 748 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 26,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 28, unit: 'in' },
    sizeLabel: "22×28\" (55.9×71.1cm) Girls' Tiered Dress",
    productBase: { type: 'image', imagePath: '/mockups/v2/girl-dress-2.png' },
    shadowPath: '/mockups/v2/girl-dress-2-shadow.png',
    highlightPath: '/mockups/v2/girl-dress-2-highlight.png',
  },

  // ─── Fabric ───
  'fabric-swatch': {
    id: 'fabric-swatch',
    name: 'Fabric Swatch',
    description: 'See your pattern on a fabric swatch',
    category: 'fabric',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 12, height: 12, unit: 'in' },
    sizeLabel: '12×12" (30.5×30.5cm) Fabric Swatch',
    productBase: { type: 'image', imagePath: '/mockups/fabric_swatch.png', maskPath: '/mockups/fabric_swatch_mask.png' },
  },

  // ─── Home Goods ───
  'throw-pillow': {
    id: 'throw-pillow',
    name: 'Throw Pillow',
    description: 'See your pattern on a throw pillow',
    category: 'home-goods',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 18, height: 18, unit: 'in' },
    sizeLabel: '18×18" (45.7×45.7cm) Throw Pillow',
    productBase: { type: 'image', imagePath: '/mockups/throw_pillow.png', maskPath: '/mockups/throw_pillow_mask.png' },
  },
  'curtain': {
    id: 'curtain',
    name: 'Curtain',
    description: 'Hanging sheer curtain panel against a wall',
    category: 'home-goods',
    canvasSize: { width: 3600, height: 4500 },
    patternArea: { x: 500, y: 358, width: 2645, height: 3883 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/curtains-mask.png',
        patternArea: { x: 500, y: 358, width: 2645, height: 3883 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 84,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 42, height: 84, unit: 'in' },
    sizeLabel: '42×84" (106.7×213.4cm) Curtain',
    productBase: { type: 'image', imagePath: '/mockups/v2/curtains.png' },
    colorOverlay: { maskPath: '/mockups/v2/curtains-wall-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/curtains-shadow.png',
    highlightPath: '/mockups/v2/curtains-highlight.png',
  },
  'tea-towel-1': {
    id: 'tea-towel-1',
    name: 'Tea Towel (Hanging)',
    description: 'Linen tea towel hanging with a hem stripe',
    category: 'home-goods',
    canvasSize: { width: 3019, height: 4500 },
    // Top-level defaults (fallback when zones absent)
    patternArea: { x: 804, y: 945, width: 1431, height: 2693 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/tea-towel-1-main-mask.png',
        patternArea: { x: 804, y: 945, width: 1431, height: 2693 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 20,
      },
      {
        id: 'bottom',
        maskPath: '/mockups/v2/tea-towel-1-bottom-mask.png',
        patternArea: { x: 1030, y: 3523, width: 1038, height: 152 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 14.5,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 20, height: 28, unit: 'in' },
    sizeLabel: '20×28" (50.8×71.1cm) Tea Towel',
    productBase: { type: 'image', imagePath: '/mockups/v2/tea-towel-1.png' },
    shadowPath: '/mockups/v2/tea-towel-1-shadow.png',
    highlightPath: '/mockups/v2/tea-towel-1-highlight.png',
  },
  'tea-towel-2': {
    id: 'tea-towel-2',
    name: 'Tea Towel (Folded)',
    description: 'Folded tea towel with hem and side stripe',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 549, y: 870, width: 1788, height: 3199 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/tea-towel-2-main-mask.png',
        patternArea: { x: 549, y: 870, width: 1788, height: 3199 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18.73,
      },
      {
        id: 'bottom',
        maskPath: '/mockups/v2/tea-towel-2-bottom-mask.png',
        patternArea: { x: 586, y: 3693, width: 1844, height: 398 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 19.32,
      },
      {
        id: 'right',
        maskPath: '/mockups/v2/tea-towel-2-right-mask.png',
        patternArea: { x: 2253, y: 906, width: 205, height: 3068 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 2.15,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 20, height: 28, unit: 'in' },
    sizeLabel: '20×28" (50.8×71.1cm) Tea Towel',
    productBase: { type: 'image', imagePath: '/mockups/v2/tea-towel-2.png' },
    shadowPath: '/mockups/v2/tea-towel-2-shadow.png',
  },
  'blanket': {
    id: 'blanket',
    name: 'Throw Blanket',
    description: 'Cozy throw blanket with gentle folds',
    category: 'home-goods',
    canvasSize: { width: 2400, height: 3577 },
    patternArea: { x: 200, y: 779, width: 1807, height: 2605 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 50, height: 60, unit: 'in' },
    sizeLabel: '50×60" (127×152.4cm) Throw Blanket',
    productBase: { type: 'image', imagePath: '/mockups/v2/throw-blanket.png', maskPath: '/mockups/v2/throw-blanket-mask.png' },
    shadowPath: '/mockups/v2/throw-blanket-shadow.png',
    highlightPath: '/mockups/v2/throw-blanket-highlight.png',
  },
  'picnic-blanket': {
    id: 'picnic-blanket',
    name: 'Picnic Blanket',
    description: 'Picnic blanket laid out on the grass',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 661, y: 0, width: 2339, height: 3251 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/picnic-blanket-main-mask.png',
        patternArea: { x: 661, y: 0, width: 2339, height: 3251 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 30,
        patternAngle: -5,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 60, height: 72, unit: 'in' },
    sizeLabel: '60×72" (152.4×182.9cm) Picnic Blanket',
    productBase: { type: 'image', imagePath: '/mockups/v2/picnic-blanket.png' },
    colorOverlay: { maskPath: '/mockups/v2/picnic-blanket-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/picnic-blanket-shadow.png',
  },
  'duvet-1': {
    id: 'duvet-1',
    name: 'Duvet Cover',
    description: 'Queen duvet cover with matching pillow',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 0, y: 1400, width: 3000, height: 2214 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/duvet-1-main-mask.png',
        patternArea: { x: 0, y: 2006, width: 3000, height: 1608 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 60,
      },
      {
        id: 'pillow',
        maskPath: '/mockups/v2/duvet-1-pillow-mask.png',
        patternArea: { x: 699, y: 1400, width: 1701, height: 482 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 26,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 90, height: 96, unit: 'in' },
    sizeLabel: '90×96" (228.6×243.8cm) Queen Duvet',
    productBase: { type: 'image', imagePath: '/mockups/v2/duvet-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/duvet-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/duvet-1-shadow.png',
    highlightPath: '/mockups/v2/duvet-1-highlight.png',
  },
  'mug-1': {
    id: 'mug-1',
    name: 'Ceramic Mug (Front)',
    description: '11oz ceramic mug viewed from the front',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 884, y: 1472, width: 1724, height: 2261 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/mug-1-mask.png',
        patternArea: { x: 884, y: 1472, width: 1724, height: 2261 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 4.3,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 8.6, height: 3.75, unit: 'in' },
    sizeLabel: '8.6×3.5" (21.8×8.9cm) 11oz Ceramic Mug',
    productBase: { type: 'image', imagePath: '/mockups/v2/mug-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/mug-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/mug-1-shadow.png',
    highlightPath: '/mockups/v2/mug-1-highlight.png',
  },
  'mug-2': {
    id: 'mug-2',
    name: 'Ceramic Mug (Angle)',
    description: '11oz ceramic mug viewed from a slight angle',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 808, y: 1440, width: 1403, height: 1872 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/mug-2-mask.png',
        patternArea: { x: 808, y: 1440, width: 1403, height: 1872 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 4,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 8.6, height: 3.75, unit: 'in' },
    sizeLabel: '8.6×3.5" (21.8×8.9cm) 11oz Ceramic Mug',
    productBase: { type: 'image', imagePath: '/mockups/v2/mug-2.png' },
    colorOverlay: { maskPath: '/mockups/v2/mug-2-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/mug-2-shadow.png',
    highlightPath: '/mockups/v2/mug-2-highlight.png',
  },
  'nursery-wall': {
    id: 'nursery-wall',
    name: 'Nursery Wall',
    description: 'Nursery room scene with wallpaper applied to wall',
    category: 'wallpaper',
    canvasSize: { width: 1000, height: 800 },
    patternArea: { x: 50, y: 30, width: 900, height: 550 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 4, wrinkleFreq: 3, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.15 },
    physicalSize: { width: 120, height: 96, unit: 'in' },
    sizeLabel: '120×96" (304.8×243.8cm) Nursery Wall',
    productBase: { type: 'procedural', brightness: 240, shape: 'flat-surface' },
  },

  // ─── Gifting ───
  'wrapping-paper': {
    id: 'wrapping-paper',
    name: 'Wrapping Paper (Gift Box)',
    description: 'See your pattern on a wrapped gift box',
    category: 'gifting',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 8, height: 8, unit: 'in' },
    sizeLabel: '8×8" (20.3×20.3cm) Wrapping Paper (Gift Box)',
    productBase: { type: 'image', imagePath: '/mockups/wrapping_paper.png', maskPath: '/mockups/wrapping_paper_mask.png' },
    colorOverlay: { maskPath: '/mockups/wrapping_paper_bow_mask.png', defaultColor: 'auto' },
  },
  'gift-bag': {
    id: 'gift-bag',
    name: 'Gift Bag',
    description: 'Paper gift bag with pattern',
    category: 'gifting',
    canvasSize: { width: 700, height: 900 },
    patternArea: { x: 100, y: 100, width: 500, height: 650 },
    perspective: { topSqueeze: 25, bottomSqueeze: 0 },
    displacement: { intensity: 6, wrinkleFreq: 4, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 10, height: 13, unit: 'in' },
    sizeLabel: '10×13" (25.4×33cm) Gift Bag',
    productBase: { type: 'procedural', brightness: 230, shape: 'flat-surface' },
  },
  'wrapping-paper-v2': {
    id: 'wrapping-paper-v2',
    name: 'Wrapping Paper (Flat Sheet)',
    description: 'Wrapping paper sheet with gentle folds',
    category: 'gifting',
    canvasSize: { width: 900, height: 800 },
    patternArea: { x: 50, y: 50, width: 800, height: 700 },
    perspective: { topSqueeze: 12, bottomSqueeze: 0 },
    displacement: { intensity: 8, wrinkleFreq: 5, type: 'fabric-drape' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 30, height: 20, unit: 'in' },
    sizeLabel: '30×20" (76.2×50.8cm) Wrapping Paper (Flat Sheet)',
    productBase: { type: 'procedural', brightness: 240, shape: 'fabric-drape' },
  },

  // ─── Wallpaper ───
  'wallpaper': {
    id: 'wallpaper',
    name: 'Wallpaper',
    description: 'See your pattern as full-room wallpaper',
    category: 'wallpaper',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 86, height: 60, unit: 'in' },
    sizeLabel: '86×60" (218.4×152.4cm) Wallpaper',
    productBase: { type: 'image', imagePath: '/mockups/wallpaper.png', maskPath: '/mockups/wallpaper_mask.png' },
  },
  'wallpaper-roll': {
    id: 'wallpaper-roll',
    name: 'Wallpaper Roll',
    description: 'Wallpaper roll partially unrolled',
    category: 'wallpaper',
    canvasSize: { width: 700, height: 900 },
    patternArea: { x: 100, y: 50, width: 500, height: 800 },
    perspective: { topSqueeze: 15, bottomSqueeze: 5 },
    displacement: { intensity: 8, wrinkleFreq: 10, type: 'cylindrical' },
    blend: { mode: 'multiply', opacity: 0.88 },
    lighting: { enabled: true, intensity: 0.3 },
    physicalSize: { width: 20, height: 33, unit: 'in' },
    sizeLabel: '20×33" (50.8×83.8cm) Wallpaper Roll',
    productBase: { type: 'procedural', brightness: 235, shape: 'cylindrical' },
  },

  // ─── Stationery ───
  'journal': {
    id: 'journal',
    name: 'A5 Journal',
    description: 'See your pattern on an A5 journal cover',
    category: 'stationery',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 5.5, height: 8.5, unit: 'in' },
    sizeLabel: '5.5×8.5" (14×21.6cm) A5 Journal',
    productBase: { type: 'image', imagePath: '/mockups/journal.png', maskPath: '/mockups/journal_mask.png' },
  },

  // ─── Accessories ───
  'silk-scarf': {
    id: 'silk-scarf',
    name: 'Silk Scarf',
    description: 'Flowing silk scarf with drape',
    category: 'accessories',
    canvasSize: { width: 3019, height: 4500 },
    patternArea: { x: 61, y: 1077, width: 2867, height: 2554 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/silk-scarf-main-mask.png',
        patternArea: { x: 61, y: 1077, width: 2867, height: 2554 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
        patternAngle: -22,
      },
      {
        id: 'corner',
        maskPath: '/mockups/v2/silk-scarf-corner-mask.png',
        patternArea: { x: 1105, y: 2576, width: 1290, height: 665 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 0.67 },
        physicalWidth: 8.11,
        patternAngle: -22,
        patternOffset: { x: 137, y: 89 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 36, height: 36, unit: 'in' },
    sizeLabel: '36×36" (91.4×91.4cm) Silk Scarf',
    productBase: { type: 'image', imagePath: '/mockups/v2/silk-scarf.png' },
    shadowPath: '/mockups/v2/silk-scarf-shadow.png',
    highlightPath: '/mockups/v2/silk-scarf-highlight.png',
  },
  'phone-case': {
    id: 'phone-case',
    name: 'Phone Case',
    description: 'Smartphone case with slight curve',
    category: 'accessories',
    canvasSize: { width: 500, height: 900 },
    patternArea: { x: 60, y: 100, width: 380, height: 650 },
    perspective: { topSqueeze: 8, bottomSqueeze: 5 },
    displacement: { intensity: 5, wrinkleFreq: 12, type: 'radial-bulge' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 3, height: 6, unit: 'in' },
    sizeLabel: '3×6" (7.6×15.2cm) Phone Case',
    productBase: { type: 'procedural', brightness: 225, shape: 'radial-bulge' },
  },
  'desk-mat': {
    id: 'desk-mat',
    name: 'Desk Mat',
    description: 'Large desk mat / mouse pad',
    category: 'accessories',
    canvasSize: { width: 1000, height: 500 },
    patternArea: { x: 50, y: 40, width: 900, height: 420 },
    perspective: { topSqueeze: 10, bottomSqueeze: 0 },
    displacement: { intensity: 3, wrinkleFreq: 4, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.92 },
    lighting: { enabled: true, intensity: 0.15 },
    physicalSize: { width: 35, height: 16, unit: 'in' },
    sizeLabel: '35×16" (88.9×40.6cm) Desk Mat',
    productBase: { type: 'procedural', brightness: 60, shape: 'flat-surface' },
  },
};

export function getV2Template(id: string): MockupV2Template | undefined {
  return mockupV2Templates[id];
}

export function getAllV2Templates(): MockupV2Template[] {
  return Object.values(mockupV2Templates);
}

export function getV2TemplatesByCategory(category: string): MockupV2Template[] {
  return Object.values(mockupV2Templates).filter(t => t.category === category);
}

export function getAllV2Categories(): string[] {
  return [...new Set(Object.values(mockupV2Templates).map(t => t.category))];
}
