import { MockupV2Template } from './types';

export const mockupV2Templates: Record<string, MockupV2Template> = {
  // ─── Apparel ───
  'onesie': {
    id: 'onesie',
    name: 'Baby Onesie',
    description: 'See your pattern on a baby onesie',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    // Union of mask1 (body) + mask2 (sleeves/snaps) bboxes.
    patternArea: { x: 185, y: 772, width: 2305, height: 3040 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'body',
        maskPath: '/mockups/v2/onesie-mask1.png',
        patternArea: { x: 185, y: 772, width: 2305, height: 3040 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 10.5,
      },
      {
        id: 'sleeves',
        maskPath: '/mockups/v2/onesie-mask2.png',
        patternArea: { x: 185, y: 772, width: 2305, height: 3040 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 10.5,
        // Offset so sleeve/snap panels don't tile in phase with the body —
        // reads as separate fabric pieces with their own grain. Same approach
        // as tote-bag trim and tea-towel-3 stripe.
        patternOffset: { x: 487, y: 281 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 10.5, height: 18, unit: 'in' },
    sizeLabel: '10.5×18" (26.7×45.7cm) Baby Onesie',
    productBase: { type: 'image', imagePath: '/mockups/v2/onesie.png' },
    colorOverlay: { maskPath: '/mockups/v2/onesie-color-mask.png', defaultColor: 'auto' },
    colorOverlayLabel: 'Onesie Trim Color',
    shadowPath: '/mockups/v2/onesie-shadow.png',
    highlightPath: '/mockups/v2/onesie-highlight.png',
  },
  'girl-dress-1': {
    id: 'girl-dress-1',
    name: "Girls' Dress",
    description: 'Photo-based girls dress with bodice, sleeves, and skirt zones',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    canvasPxPerInch: 84,
    patternArea: { x: 472, y: 934, width: 2020, height: 3219 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'bodice',
        maskPath: '/mockups/v2/girl-dress-1-bodice-mask.png',
        patternArea: { x: 772, y: 934, width: 1445, height: 1848 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 12,
      },
      {
        id: 'sleeves',
        maskPath: '/mockups/v2/girl-dress-1-sleeves-mask.png',
        patternArea: { x: 573, y: 1031, width: 1879, height: 687 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
      },
      {
        id: 'skirt',
        maskPath: '/mockups/v2/girl-dress-1-skirt-mask.png',
        patternArea: { x: 472, y: 2726, width: 2020, height: 1427 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 26, unit: 'in' },
    sizeLabel: "22×26\" (55.9×66cm) Girls' Dress",
    productBase: { type: 'image', imagePath: '/mockups/v2/girl-dress-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/girl-dress-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/girl-dress-1-shadow.png',
    highlightPath: '/mockups/v2/girl-dress-1-highlight.png',
  },
  'swim-trunks-1': {
    id: 'swim-trunks-1',
    name: "Boys' Swim Trunks",
    description: 'Swim trunks with a contrast hem panel',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 106, y: 1138, width: 2672, height: 2331 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/swim-trunks-1-mask.png',
        patternArea: { x: 111, y: 1138, width: 2667, height: 2226 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
        patternAngle: 10,
      },
      {
        id: 'hem',
        maskPath: '/mockups/v2/swim-trunks-1-hem-mask.png',
        patternArea: { x: 106, y: 2717, width: 2660, height: 752 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 22,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 19, unit: 'in' },
    sizeLabel: "22×19\" (55.9×48.3cm) Boys' Swim Trunks",
    productBase: { type: 'image', imagePath: '/mockups/v2/swim-trunks-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/swim-trunks-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/swim-trunks-1-shadow.png',
    highlightPath: '/mockups/v2/swim-trunks-1-highlight.png',
  },
  'swimsuit-kids-2': {
    id: 'swimsuit-kids-2',
    name: "Kids' One-Piece Swimsuit",
    description: 'One-piece swimsuit for kids',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 525, y: 610, width: 1868, height: 3272 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/swimsuit-kids-2-mask.png',
        patternArea: { x: 525, y: 610, width: 1868, height: 3272 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 12,
        patternAngle: 14,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 12, height: 22, unit: 'in' },
    sizeLabel: "12×22\" (30.5×55.9cm) Kids' Swimsuit",
    productBase: { type: 'image', imagePath: '/mockups/v2/swimsuit-kids-2.png' },
    colorOverlay: { maskPath: '/mockups/v2/swimsuit-kids-2-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/swimsuit-kids-2-shadow.png',
    highlightPath: '/mockups/v2/swimsuit-kids-2-highlight.png',
  },
  'apron': {
    id: 'apron',
    name: 'Apron',
    description: 'Adult bib apron with full coverage',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 0, y: 236, width: 2572, height: 3917 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/apron-main-mask.png',
        patternArea: { x: 0, y: 236, width: 2572, height: 3917 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 28,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 28, height: 32, unit: 'in' },
    sizeLabel: '28×32" (71.1×81.3cm) Apron',
    productBase: { type: 'image', imagePath: '/mockups/v2/apron.png' },
    colorOverlay: { maskPath: '/mockups/v2/apron-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/apron-shadow.png',
    highlightPath: '/mockups/v2/apron-highlight.png',
  },
  'boys-pjs': {
    id: 'boys-pjs',
    name: "Boys' Pajamas",
    description: "Kids' 2-piece pajama set with top and pants zones",
    category: 'apparel',
    canvasSize: { width: 3000, height: 4472 },
    patternArea: { x: 245, y: 588, width: 2579, height: 3527 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'top',
        maskPath: '/mockups/v2/boys-pjs-top-mask.png',
        patternArea: { x: 245, y: 588, width: 2373, height: 1610 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
      },
      {
        id: 'pants',
        maskPath: '/mockups/v2/boys-pjs-pants-mask.png',
        patternArea: { x: 488, y: 1968, width: 2336, height: 2147 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 30, unit: 'in' },
    sizeLabel: "22×30\" (55.9×76.2cm) Boys' Pajamas",
    productBase: { type: 'image', imagePath: '/mockups/v2/boys-pjs.png' },
    colorOverlay: { maskPath: '/mockups/v2/boys-pjs-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/boys-pjs-shadow.png',
    highlightPath: '/mockups/v2/boys-pjs-highlight.png',
  },
  'girl-dress-2': {
    id: 'girl-dress-2',
    name: "Girls' Tiered Dress",
    description: 'Tiered girls dress with bodice and three ruffle panels',
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    canvasPxPerInch: 69,
    patternArea: { x: 514, y: 905, width: 1866, height: 2217 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'bodice',
        maskPath: '/mockups/v2/girl-dress-2-bodice-mask.png',
        patternArea: { x: 1237, y: 905, width: 606, height: 744 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 9,
      },
      {
        id: 'top',
        maskPath: '/mockups/v2/girl-dress-2-top-mask.png',
        patternArea: { x: 1038, y: 1562, width: 966, height: 608 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 14,
      },
      {
        id: 'middle',
        maskPath: '/mockups/v2/girl-dress-2-middle-mask.png',
        patternArea: { x: 880, y: 2063, width: 1284, height: 466 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
      },
      {
        id: 'bottom',
        maskPath: '/mockups/v2/girl-dress-2-bottom-mask.png',
        patternArea: { x: 514, y: 2374, width: 1866, height: 748 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 26,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 28, unit: 'in' },
    sizeLabel: "22×28\" (55.9×71.1cm) Girls' Tiered Dress",
    productBase: { type: 'image', imagePath: '/mockups/v2/girl-dress-2.png' },
    shadowPath: '/mockups/v2/girl-dress-2-shadow.png',
    highlightPath: '/mockups/v2/girl-dress-2-highlight.png',
  },

  // ─── Fabric ───
  'fabric-swatch': {
    id: 'fabric-swatch',
    name: 'Fabric Swatch',
    description: 'See your pattern on a fabric swatch',
    category: 'fabric',
    canvasSize: { width: 3000, height: 4500 },
    // Union of mask1 (body) + mask2 (detail) bboxes.
    patternArea: { x: 494, y: 1024, width: 2083, height: 2385 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'body',
        maskPath: '/mockups/v2/fabric-swatch-mask1.png',
        patternArea: { x: 494, y: 1024, width: 2083, height: 2385 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 12,
      },
      {
        id: 'detail',
        maskPath: '/mockups/v2/fabric-swatch-mask2.png',
        patternArea: { x: 494, y: 1024, width: 2083, height: 2385 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 12,
        // User-requested offset so mask2 doesn't tile in phase with mask1.
        // Same trick as tote-bag trim and tea-towel-3 stripe.
        patternOffset: { x: 487, y: 281 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 12, height: 12, unit: 'in' },
    sizeLabel: '12×12" (30.5×30.5cm) Fabric Swatch',
    productBase: { type: 'image', imagePath: '/mockups/v2/fabric-swatch.png' },
    shadowPath: '/mockups/v2/fabric-swatch-shadow.png',
    highlightPath: '/mockups/v2/fabric-swatch-highlight.png',
  },

  // ─── Home Goods ───
  'throw-pillow': {
    id: 'throw-pillow',
    name: 'Throw Pillow',
    description: 'See your pattern on a throw pillow',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 504, y: 1315, width: 2026, height: 1922 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'pillow',
        maskPath: '/mockups/v2/throw-pillow-mask.png',
        patternArea: { x: 504, y: 1315, width: 2026, height: 1922 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 18, height: 18, unit: 'in' },
    sizeLabel: '18×18" (45.7×45.7cm) Throw Pillow',
    productBase: { type: 'image', imagePath: '/mockups/v2/throw-pillow.png' },
    shadowPath: '/mockups/v2/throw-pillow-shadow.png',
    highlightPath: '/mockups/v2/throw-pillow-highlight.png',
  },
  'curtain': {
    id: 'curtain',
    name: 'Curtain',
    description: 'Hanging sheer curtain panel against a wall',
    category: 'home-goods',
    canvasSize: { width: 3600, height: 4500 },
    patternArea: { x: 500, y: 358, width: 2645, height: 3883 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/curtains-mask.png',
        patternArea: { x: 500, y: 358, width: 2645, height: 3883 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 84,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 42, height: 84, unit: 'in' },
    sizeLabel: '42×84" (106.7×213.4cm) Curtain',
    productBase: { type: 'image', imagePath: '/mockups/v2/curtains.png' },
    colorOverlay: { maskPath: '/mockups/v2/curtains-wall-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/curtains-shadow.png',
    highlightPath: '/mockups/v2/curtains-highlight.png',
  },
  'tea-towel-1': {
    id: 'tea-towel-1',
    name: 'Tea Towel (Hanging)',
    description: 'Linen tea towel hanging with a hem stripe',
    category: 'home-goods',
    canvasSize: { width: 3019, height: 4500 },
    // Top-level defaults (fallback when zones absent)
    patternArea: { x: 804, y: 945, width: 1431, height: 2693 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/tea-towel-1-main-mask.png',
        patternArea: { x: 804, y: 945, width: 1431, height: 2693 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 20,
      },
      {
        id: 'bottom',
        maskPath: '/mockups/v2/tea-towel-1-bottom-mask.png',
        patternArea: { x: 1030, y: 3523, width: 1038, height: 152 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 14.5,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 20, height: 28, unit: 'in' },
    sizeLabel: '20×28" (50.8×71.1cm) Tea Towel',
    productBase: { type: 'image', imagePath: '/mockups/v2/tea-towel-1.png' },
    shadowPath: '/mockups/v2/tea-towel-1-shadow.png',
    highlightPath: '/mockups/v2/tea-towel-1-highlight.png',
  },
  'tea-towel-3': {
    id: 'tea-towel-3',
    name: 'Tea Towel (Folded)',
    description: 'Folded tea towel with body and stripe detail',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    // Union of mask1 (body) + mask2 (stripe) bboxes.
    patternArea: { x: 637, y: 847, width: 1788, height: 3206 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'body',
        maskPath: '/mockups/v2/tea-towel3-mask1.png',
        patternArea: { x: 637, y: 847, width: 1788, height: 3206 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18.73,
      },
      {
        id: 'stripe',
        maskPath: '/mockups/v2/tea-towel3-mask2.png',
        patternArea: { x: 637, y: 847, width: 1788, height: 3206 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18.73,
        // Offset so the stripe doesn't tile in phase with the body — reads as a
        // distinct band/fold rather than a continuous surface. Same trick as
        // tote-bag trim; sized to fall clearly out of phase with common tiles.
        patternOffset: { x: 487, y: 281 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 20, height: 28, unit: 'in' },
    sizeLabel: '20×28" (50.8×71.1cm) Tea Towel',
    productBase: { type: 'image', imagePath: '/mockups/v2/tea-towel3.png' },
    shadowPath: '/mockups/v2/tea-towel3-shadow.png',
    highlightPath: '/mockups/v2/tea-towel3-highlight.png',
  },
  'picnic-blanket': {
    id: 'picnic-blanket',
    name: 'Picnic Blanket',
    description: 'Picnic blanket laid out on the grass',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 661, y: 0, width: 2339, height: 3251 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/picnic-blanket-main-mask.png',
        patternArea: { x: 661, y: 0, width: 2339, height: 3251 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 30,
        patternAngle: -5,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 60, height: 72, unit: 'in' },
    sizeLabel: '60×72" (152.4×182.9cm) Picnic Blanket',
    productBase: { type: 'image', imagePath: '/mockups/v2/picnic-blanket.png' },
    colorOverlay: { maskPath: '/mockups/v2/picnic-blanket-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/picnic-blanket-shadow.png',
  },
  'duvet-1': {
    id: 'duvet-1',
    name: 'Duvet Cover',
    description: 'Queen duvet cover with matching pillow',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    canvasPxPerInch: 50,
    patternArea: { x: 0, y: 1400, width: 3000, height: 2214 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/duvet-1-main-mask.png',
        patternArea: { x: 0, y: 2006, width: 3000, height: 1608 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 60,
      },
      {
        id: 'pillow',
        maskPath: '/mockups/v2/duvet-1-pillow-mask.png',
        patternArea: { x: 699, y: 1400, width: 1701, height: 482 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 26,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 90, height: 96, unit: 'in' },
    sizeLabel: '90×96" (228.6×243.8cm) Queen Duvet',
    productBase: { type: 'image', imagePath: '/mockups/v2/duvet-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/duvet-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/duvet-1-shadow.png',
    highlightPath: '/mockups/v2/duvet-1-highlight.png',
  },
  'mug-1': {
    id: 'mug-1',
    name: 'Ceramic Mug (Front)',
    description: '11oz ceramic mug viewed from the front',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 884, y: 1472, width: 1724, height: 2261 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/mug-1-mask.png',
        patternArea: { x: 884, y: 1472, width: 1724, height: 2261 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 4.3,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 8.6, height: 3.75, unit: 'in' },
    sizeLabel: '8.6×3.5" (21.8×8.9cm) 11oz Ceramic Mug',
    productBase: { type: 'image', imagePath: '/mockups/v2/mug-1.png' },
    colorOverlay: { maskPath: '/mockups/v2/mug-1-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/mug-1-shadow.png',
    highlightPath: '/mockups/v2/mug-1-highlight.png',
  },
  'mug-2': {
    id: 'mug-2',
    name: 'Ceramic Mug (Angle)',
    description: '11oz ceramic mug viewed from a slight angle',
    category: 'home-goods',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 808, y: 1440, width: 1403, height: 1872 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/mug-2-mask.png',
        patternArea: { x: 808, y: 1440, width: 1403, height: 1872 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 4,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 8.6, height: 3.75, unit: 'in' },
    sizeLabel: '8.6×3.5" (21.8×8.9cm) 11oz Ceramic Mug',
    productBase: { type: 'image', imagePath: '/mockups/v2/mug-2.png' },
    colorOverlay: { maskPath: '/mockups/v2/mug-2-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/mug-2-shadow.png',
    highlightPath: '/mockups/v2/mug-2-highlight.png',
  },
  'nursery-wall': {
    id: 'nursery-wall',
    name: 'Nursery Wall',
    description: 'Nursery room scene with wallpaper applied to wall',
    category: 'wallpaper',
    canvasSize: { width: 1000, height: 800 },
    patternArea: { x: 50, y: 30, width: 900, height: 550 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 4, wrinkleFreq: 3, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.15 },
    physicalSize: { width: 120, height: 96, unit: 'in' },
    sizeLabel: '120×96" (304.8×243.8cm) Nursery Wall',
    productBase: { type: 'procedural', brightness: 240, shape: 'flat-surface' },
  },

  // ─── Gifting ───
  'wrapping-paper': {
    // ID preserved for backward-compat (referenced in __tests__/templateRegistry.test.ts).
    // Asset family is now `gift-box-*` since v2 reshoot.
    id: 'wrapping-paper',
    name: 'Wrapping Paper (Gift Box)',
    description: 'See your pattern on a wrapped gift box',
    category: 'gifting',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 417, y: 1045, width: 2185, height: 2271 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'box',
        maskPath: '/mockups/v2/gift-box-mask.png',
        patternArea: { x: 417, y: 1045, width: 2185, height: 2271 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 8,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 8, height: 8, unit: 'in' },
    sizeLabel: '8×8" (20.3×20.3cm) Wrapping Paper (Gift Box)',
    productBase: { type: 'image', imagePath: '/mockups/v2/gift-box.png' },
    colorOverlay: { maskPath: '/mockups/v2/gift-box-color-mask.png', defaultColor: 'auto' },
    colorOverlayLabel: 'Bow Color',
    shadowPath: '/mockups/v2/gift-box-shadow.png',
    highlightPath: '/mockups/v2/gift-box-highlight.png',
  },
  'gift-bag': {
    id: 'gift-bag',
    name: 'Gift Bag',
    description: 'Paper gift bag with pattern',
    category: 'gifting',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 655, y: 1330, width: 1828, height: 2329 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 10, height: 13, unit: 'in' },
    sizeLabel: '10×13" (25.4×33cm) Gift Bag',
    productBase: { type: 'image', imagePath: '/mockups/v2/gift-bag.png', maskPath: '/mockups/v2/gift-bag-mask.png' },
    shadowPath: '/mockups/v2/gift-bag-shadow.png',
    highlightPath: '/mockups/v2/gift-bag-highlight.png',
  },
  'wrapping-paper-v2': {
    id: 'wrapping-paper-v2',
    name: 'Wrapping Paper (Flat Sheet)',
    description: 'Wrapping paper sheet with gentle folds',
    category: 'gifting',
    canvasSize: { width: 900, height: 800 },
    patternArea: { x: 50, y: 50, width: 800, height: 700 },
    perspective: { topSqueeze: 12, bottomSqueeze: 0 },
    displacement: { intensity: 8, wrinkleFreq: 5, type: 'fabric-drape' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 30, height: 20, unit: 'in' },
    sizeLabel: '30×20" (76.2×50.8cm) Wrapping Paper (Flat Sheet)',
    productBase: { type: 'procedural', brightness: 240, shape: 'fabric-drape' },
  },

  // ─── Wallpaper ───
  'wallpaper': {
    // ID preserved for backward-compat (referenced in __tests__/templateRegistry.test.ts
    // and __tests__/galleryModal.test.ts). Asset family is now `entry-wallpaper-*`.
    id: 'wallpaper',
    name: 'Entry Wallpaper',
    description: 'See your pattern as wallpaper in an entryway scene',
    category: 'wallpaper',
    canvasSize: { width: 3000, height: 4472 },
    patternArea: { x: 0, y: 0, width: 3000, height: 3319 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'wall',
        maskPath: '/mockups/v2/entry-wallpaper-mask.png',
        patternArea: { x: 0, y: 0, width: 3000, height: 3319 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 86,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 86, height: 60, unit: 'in' },
    sizeLabel: '86×60" (218.4×152.4cm) Entry Wallpaper',
    productBase: { type: 'image', imagePath: '/mockups/v2/entry-wallpaper.png' },
    colorOverlay: { maskPath: '/mockups/v2/entry-wallpaper-color-mask.png', defaultColor: 'auto' },
    colorOverlayLabel: 'Accent Color',
    shadowPath: '/mockups/v2/entry-wallpaper-shadow.png',
    highlightPath: '/mockups/v2/entry-wallpaper-highlight.png',
  },
  'wallpaper-roll': {
    id: 'wallpaper-roll',
    name: 'Wallpaper Roll',
    description: 'Wallpaper roll partially unrolled',
    category: 'wallpaper',
    canvasSize: { width: 700, height: 900 },
    patternArea: { x: 100, y: 50, width: 500, height: 800 },
    perspective: { topSqueeze: 15, bottomSqueeze: 5 },
    displacement: { intensity: 8, wrinkleFreq: 10, type: 'cylindrical' },
    blend: { mode: 'multiply', opacity: 0.88 },
    lighting: { enabled: true, intensity: 0.3 },
    physicalSize: { width: 20, height: 33, unit: 'in' },
    sizeLabel: '20×33" (50.8×83.8cm) Wallpaper Roll',
    productBase: { type: 'procedural', brightness: 235, shape: 'cylindrical' },
  },

  // ─── Stationery ───
  'journal': {
    id: 'journal',
    name: 'A5 Journal',
    description: 'See your pattern on an A5 journal cover',
    category: 'stationery',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 778, y: 1285, width: 1434, height: 2043 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'cover',
        maskPath: '/mockups/v2/journal-mask.png',
        patternArea: { x: 778, y: 1285, width: 1434, height: 2043 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 5.5,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 5.5, height: 8.5, unit: 'in' },
    sizeLabel: '5.5×8.5" (14×21.6cm) A5 Journal',
    productBase: { type: 'image', imagePath: '/mockups/v2/journal.png' },
  },

  // ─── Accessories ───
  'silk-scarf': {
    id: 'silk-scarf',
    name: 'Silk Scarf',
    description: 'Flowing silk scarf with drape',
    category: 'accessories',
    canvasSize: { width: 3019, height: 4500 },
    patternArea: { x: 61, y: 1077, width: 2867, height: 2554 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/silk-scarf-main-mask.png',
        patternArea: { x: 61, y: 1077, width: 2867, height: 2554 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 18,
        patternAngle: 21,
      },
      {
        id: 'corner',
        maskPath: '/mockups/v2/silk-scarf-corner-mask.png',
        patternArea: { x: 1105, y: 2576, width: 1290, height: 665 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 0.67 },
        physicalWidth: 8.11,
        patternAngle: 21,
        patternOffset: { x: 137, y: 89 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 36, height: 36, unit: 'in' },
    sizeLabel: '36×36" (91.4×91.4cm) Silk Scarf',
    productBase: { type: 'image', imagePath: '/mockups/v2/silk-scarf.png' },
    shadowPath: '/mockups/v2/silk-scarf-shadow.png',
    highlightPath: '/mockups/v2/silk-scarf-highlight.png',
  },
  'mens-tie': {
    id: 'mens-tie',
    name: "Men's Tie",
    description: "Necktie worn with a jacket, with separate knot and body zones",
    category: 'accessories',
    canvasSize: { width: 3000, height: 4500 },
    canvasPxPerInch: 177,
    patternArea: { x: 1230, y: 941, width: 621, height: 3358 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'main',
        maskPath: '/mockups/v2/mens-tie-mask.png',
        patternArea: { x: 1230, y: 1000, width: 621, height: 3299 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 3.5,
      },
      {
        id: 'knot',
        maskPath: '/mockups/v2/mens-tie-knot-mask.png',
        patternArea: { x: 1290, y: 941, width: 418, height: 428 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 2.0,
        patternOffset: { x: 80, y: 50 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 3.5, height: 22, unit: 'in' },
    sizeLabel: '3.5×22" (8.9×55.9cm) Men\'s Tie',
    productBase: { type: 'image', imagePath: '/mockups/v2/mens-tie.png' },
    colorOverlay: { maskPath: '/mockups/v2/mens-tie-color-mask.png', defaultColor: 'auto' },
    colorOverlayDefaultEnabled: false,
    shadowPath: '/mockups/v2/mens-tie-shadow.png',
    additionalShadowPaths: ['/mockups/v2/mens-tie-jacket-shadow.png'],
    additionalShadowDefaultEnableds: [false],
    shadowLabel: 'Tie shadow',
    additionalShadowLabels: ['Jacket shadow'],
    highlightPath: '/mockups/v2/mens-tie-highlight.png',
    additionalHighlightPaths: ['/mockups/v2/mens-tie-jacket-highlight.png'],
    additionalHighlightDefaultEnableds: [false],
    highlightLabel: 'Tie highlight',
    additionalHighlightLabels: ['Jacket highlight'],
    colorOverlayLabel: 'Jacket color',
  },
  'phone-case': {
    id: 'phone-case',
    name: 'Phone Case',
    description: 'Smartphone case with slight curve',
    category: 'accessories',
    canvasSize: { width: 3000, height: 4472 },
    patternArea: { x: 690, y: 1027, width: 1639, height: 2485 },
    patternAngle: 15,
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 3, height: 6, unit: 'in' },
    sizeLabel: '3×6" (7.6×15.2cm) Phone Case',
    productBase: { type: 'image', imagePath: '/mockups/v2/phone-case.png', maskPath: '/mockups/v2/phone-case-mask.png' },
    shadowPath: '/mockups/v2/phone-case-shadow.png',
    highlightPath: '/mockups/v2/phone-case-highlight.png',
  },
  'desk-mat': {
    id: 'desk-mat',
    name: 'Desk Mat',
    description: 'Large desk mat / mouse pad',
    category: 'accessories',
    canvasSize: { width: 3000, height: 4500 },
    patternArea: { x: 0, y: 862, width: 3000, height: 3638 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 35, height: 16, unit: 'in' },
    sizeLabel: '35×16" (88.9×40.6cm) Desk Mat',
    productBase: { type: 'image', imagePath: '/mockups/v2/desk-mat.png', maskPath: '/mockups/v2/desk-mat-mask.png' },
    shadowPath: '/mockups/v2/desk-mat-shadow.png',
    highlightPath: '/mockups/v2/desk-mat-highlight.png',
  },
  'tote-bag': {
    id: 'tote-bag',
    name: 'Tote Bag',
    description: 'Canvas tote bag with front-panel and edge-trim regions',
    category: 'accessories',
    canvasSize: { width: 3000, height: 4500 },
    // Union of mask1 (body) + mask2 (trim) bboxes.
    patternArea: { x: 420, y: 1456, width: 2061, height: 1747 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'body',
        maskPath: '/mockups/v2/tote-bag-mask1.png',
        patternArea: { x: 420, y: 1456, width: 2061, height: 1747 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 15,
      },
      {
        id: 'trim',
        maskPath: '/mockups/v2/tote-bag-mask2.png',
        patternArea: { x: 420, y: 1456, width: 2061, height: 1747 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 15,
        // Offset so the trim's pattern doesn't line up with the body panel —
        // reads as a separate side gusset rather than a continuous front.
        // Roughly 24% / 16% of patternArea (W=2061, H=1747) so it falls clearly
        // out of phase with common pattern tile sizes (small offsets get
        // swallowed by tiles that repeat at multiples of the shift).
        patternOffset: { x: 487, y: 281 },
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 15, height: 14, unit: 'in' },
    sizeLabel: '15×14" (38.1×35.6cm) Tote Bag',
    productBase: { type: 'image', imagePath: '/mockups/v2/tote-bag.png' },
    colorOverlay: { maskPath: '/mockups/v2/tote-bag-color-mask.png', defaultColor: 'auto' },
    colorOverlayLabel: 'Handle Color',
    shadowPath: '/mockups/v2/tote-bag-shadow.png',
    highlightPath: '/mockups/v2/tote-bag-highlight.png',
  },
  'mens-dress-shirt': {
    id: 'mens-dress-shirt',
    name: "Men's Dress Shirt",
    description: "Men's button-down dress shirt with multiple panel masks (slightly offset so pattern doesn't line up across seams)",
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    // Union of the 3 panel mask bboxes.
    patternArea: { x: 0, y: 180, width: 3000, height: 4320 },
    // canvasPxPerInch unifies pattern density across all 3 panel zones — same
    // fabric across the whole shirt. 3000px / 24" = 125 px/in.
    canvasPxPerInch: 125,
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    zones: [
      {
        id: 'panel-1',
        maskPath: '/mockups/v2/mens-dress-shirt-mask1.png',
        patternArea: { x: 0, y: 484, width: 3000, height: 4016 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
        patternAngle: 15,
      },
      {
        id: 'panel-2',
        maskPath: '/mockups/v2/mens-dress-shirt-mask2.png',
        // Width widened from 2274 → 2310 to fully contain mask2 (actual right
        // edge at x=2307); without this, the rightmost ~33px of mask2 ends up
        // outside the tile canvas and gets no pattern.
        patternArea: { x: 0, y: 734, width: 2310, height: 3766 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
        // Small shift so this panel doesn't line up with panel-1 — simulates
        // a real garment where each cut piece starts at a different point in
        // the bolt of fabric.
        patternOffset: { x: 73, y: 41 },
        patternAngle: 45,
      },
      {
        id: 'panel-3',
        maskPath: '/mockups/v2/mens-dress-shirt-mask3.png',
        // Width widened from 2203 → 2280 to fully contain mask3 (actual right
        // edge at x=2273). Previously the rightmost ~70px of mask3 (a vertical
        // strip down the placket area, visible as a blank gap near the buttons)
        // fell outside the tile canvas and received no pattern.
        patternArea: { x: 0, y: 180, width: 2280, height: 4320 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
        patternOffset: { x: -55, y: 89 },
        patternAngle: 15,
      },
      {
        id: 'panel-4',
        maskPath: '/mockups/v2/mens-dress-shirt-mask4.png',
        patternArea: { x: 582, y: 180, width: 1621, height: 1302 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
        patternOffset: { x: 32, y: -67 },
        patternAngle: 15,
      },
      {
        id: 'panel-5',
        maskPath: '/mockups/v2/mens-dress-shirt-mask5.png',
        patternArea: { x: 0, y: 2993, width: 1101, height: 1507 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 1.0 },
        physicalWidth: 24,
        patternOffset: { x: -91, y: 23 },
        patternAngle: 53,
      },
    ],
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 24, height: 30, unit: 'in' },
    sizeLabel: "24×30\" (61×76.2cm) Men's Dress Shirt",
    productBase: { type: 'image', imagePath: '/mockups/v2/mens-dress-shirt.png' },
    colorOverlay: { maskPath: '/mockups/v2/mens-dress-shirt-color-mask.png', defaultColor: 'auto' },
    shadowPath: '/mockups/v2/mens-dress-shirt-shadow.png',
    highlightPath: '/mockups/v2/mens-dress-shirt-highlight.png',
  },
  'womens-blouse': {
    id: 'womens-blouse',
    name: "Women's Blouse",
    description: "Women's blouse, full-coverage pattern",
    category: 'apparel',
    canvasSize: { width: 3000, height: 4500 },
    // Mask-derived bbox: blouse occupies y≈799..4499, full width.
    patternArea: { x: 0, y: 799, width: 3000, height: 3701 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 1.0 },
    lighting: { enabled: false, intensity: 0 },
    physicalSize: { width: 22, height: 26, unit: 'in' },
    sizeLabel: '22×26" (55.9×66cm) Women\'s Blouse',
    productBase: { type: 'image', imagePath: '/mockups/v2/womens-blouse.png', maskPath: '/mockups/v2/womens-blouse-mask.png' },
    shadowPath: '/mockups/v2/womens-blouse-shadow.png',
    highlightPath: '/mockups/v2/womens-blouse-highlight.png',
  },
};

export function getV2Template(id: string): MockupV2Template | undefined {
  return mockupV2Templates[id];
}

export function getAllV2Templates(): MockupV2Template[] {
  return Object.values(mockupV2Templates);
}

export function getV2TemplatesByCategory(category: string): MockupV2Template[] {
  return Object.values(mockupV2Templates).filter(t => t.category === category);
}

export function getAllV2Categories(): string[] {
  return [...new Set(Object.values(mockupV2Templates).map(t => t.category))];
}
