import { MockupV2Template } from './types';

export const mockupV2Templates: Record<string, MockupV2Template> = {
  // ─── Apparel ───
  'onesie': {
    id: 'onesie',
    name: 'Baby Onesie',
    description: 'See your pattern on a baby onesie',
    category: 'apparel',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 10.5, height: 18, unit: 'in' },
    sizeLabel: '10.5×18" (26.7×45.7cm) Baby Onesie',
    productBase: { type: 'image', imagePath: '/mockups/onesie.png', maskPath: '/mockups/onesie_mask_new.png' },
    colorOverlay: { maskPath: '/mockups/onesie_mask_color.png', defaultColor: 'auto' },
  },
  'tshirt-dress': {
    id: 'tshirt-dress',
    name: "Children's T-Shirt Dress",
    description: 'A-line children\'s t-shirt dress with flowing fabric',
    category: 'apparel',
    canvasSize: { width: 1856, height: 2304 },
    // Top-level defaults (used if zones are missing)
    patternArea: { x: 430, y: 421, width: 1010, height: 1700 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.85 },
    // Multi-zone: bodice and skirt rendered independently
    // patternArea coords derived from actual mask white-pixel bounds
    zones: [
      {
        id: 'bodice',
        maskPath: '/mockups/v2/tshirt-dress_bodice.png',
        patternArea: { x: 453, y: 421, width: 960, height: 896 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 0.85 },
        physicalWidth: 13.5,
      },
      {
        id: 'skirt',
        maskPath: '/mockups/v2/tshirt-dress_skirt.png',
        patternArea: { x: 430, y: 1307, width: 1007, height: 804 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 8, wrinkleFreq: 5, type: 'fabric-drape' },
        blend: { mode: 'multiply', opacity: 0.85 },
        physicalWidth: 18,
      },
    ],
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 13.5, height: 20.5, unit: 'in' },
    sizeLabel: '13.5×20.5" (34×52cm) Kids T-Shirt Dress',
    productBase: { type: 'image', imagePath: '/mockups/v2/tshirt-dress.png' },
  },
  'womens-skirt': {
    id: 'womens-skirt',
    name: "Women's Skirt",
    description: 'A-line skirt in a field — photo-based mockup',
    category: 'apparel',
    canvasSize: { width: 3712, height: 4608 },
    // patternArea from mask white-pixel bounds (Pillow scan)
    patternArea: { x: 1023, y: 2113, width: 1271, height: 1570 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 8, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'source-over', opacity: 1.0 },
    lighting: { enabled: true, intensity: 0.7 },
    displacementMapPath: '/mockups/v2/womans-skirt-field-displacement.png',
    physicalSize: { width: 20, height: 24, unit: 'in' },
    sizeLabel: "20×24\" (50.8×61cm) Women's Skirt",
    productBase: { type: 'image', imagePath: '/mockups/v2/womans-skirt-field.png', maskPath: '/mockups/v2/womans-skirt-field-mask.png' },
  },

  // ─── Fabric ───
  'fabric-swatch': {
    id: 'fabric-swatch',
    name: 'Fabric Swatch',
    description: 'See your pattern on a fabric swatch',
    category: 'fabric',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 12, height: 12, unit: 'in' },
    sizeLabel: '12×12" (30.5×30.5cm) Fabric Swatch',
    productBase: { type: 'image', imagePath: '/mockups/fabric_swatch.png', maskPath: '/mockups/fabric_swatch_mask.png' },
  },

  // ─── Home Goods ───
  'throw-pillow': {
    id: 'throw-pillow',
    name: 'Throw Pillow',
    description: 'See your pattern on a throw pillow',
    category: 'home-goods',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 18, height: 18, unit: 'in' },
    sizeLabel: '18×18" (45.7×45.7cm) Throw Pillow',
    productBase: { type: 'image', imagePath: '/mockups/throw_pillow.png', maskPath: '/mockups/throw_pillow_mask.png' },
  },
  'tablecloth': {
    id: 'tablecloth',
    name: 'Tablecloth',
    description: 'Linen tablecloth draped over a table with props',
    category: 'home-goods',
    canvasSize: { width: 3712, height: 4608 },
    // Top-level defaults (used if zones are missing)
    patternArea: { x: 0, y: 1906, width: 3089, height: 1668 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.85 },
    // Shared tiling: one continuous pattern across all zones (union bounding box)
    sharedPatternArea: { x: 0, y: 1906, width: 3360, height: 2137 },
    // Multi-zone: top surface, front drape, corner drape — same pattern, different displacement
    zones: [
      {
        id: 'top',
        maskPath: '/mockups/v2/tablecloth-top-mask.png',
        patternArea: { x: 0, y: 1906, width: 3089, height: 305 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0, rightSqueeze: 305 },
        displacement: { intensity: 2, wrinkleFreq: 2, type: 'flat-surface' },
        blend: { mode: 'multiply', opacity: 0.85 },
        foreshorten: 1,
      },
      {
        id: 'front',
        maskPath: '/mockups/v2/tablecloth-front-mask.png',
        patternArea: { x: 0, y: 2210, width: 3043, height: 1363 },
        perspective: { topSqueeze: 0, bottomSqueeze: 0 },
        displacement: { intensity: 4, wrinkleFreq: 3, type: 'vertical-drape' },
        blend: { mode: 'multiply', opacity: 0.85 },
      },
      {
        id: 'corner',
        maskPath: '/mockups/v2/tablecloth-corner-mask.png',
        patternArea: { x: 2847, y: 2210, width: 513, height: 1833 },
        perspective: { topSqueeze: 15, bottomSqueeze: 5 },
        displacement: { intensity: 4, wrinkleFreq: 3, type: 'fabric-drape' },
        blend: { mode: 'multiply', opacity: 0.85 },
      },
    ],
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 60, height: 40, unit: 'in' },
    sizeLabel: '60×40" (152.4×101.6cm) Tablecloth',
    productBase: { type: 'image', imagePath: '/mockups/v2/tablecloth.png' },
  },
  'curtain': {
    id: 'curtain',
    name: 'Curtain',
    description: 'Hanging curtain panel with vertical draping',
    category: 'home-goods',
    canvasSize: { width: 600, height: 1000 },
    patternArea: { x: 50, y: 30, width: 500, height: 940 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 18, wrinkleFreq: 6, type: 'vertical-drape' },
    blend: { mode: 'multiply', opacity: 0.85 },
    lighting: { enabled: true, intensity: 0.35 },
    physicalSize: { width: 42, height: 84, unit: 'in' },
    sizeLabel: '42×84" (106.7×213.4cm) Curtain',
    productBase: { type: 'procedural', brightness: 200, shape: 'vertical-drape' },
  },
  'blanket': {
    id: 'blanket',
    name: 'Blanket',
    description: 'Soft throw blanket with gentle folds',
    category: 'home-goods',
    canvasSize: { width: 900, height: 800 },
    patternArea: { x: 50, y: 50, width: 800, height: 700 },
    perspective: { topSqueeze: 10, bottomSqueeze: 5 },
    displacement: { intensity: 12, wrinkleFreq: 5, type: 'fabric-drape' },
    blend: { mode: 'multiply', opacity: 0.87 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 50, height: 60, unit: 'in' },
    sizeLabel: '50×60" (127×152.4cm) Blanket',
    productBase: { type: 'procedural', brightness: 215, shape: 'fabric-drape' },
  },
  'nursery-wall': {
    id: 'nursery-wall',
    name: 'Nursery Wall',
    description: 'Nursery room scene with wallpaper applied to wall',
    category: 'wallpaper',
    canvasSize: { width: 1000, height: 800 },
    patternArea: { x: 50, y: 30, width: 900, height: 550 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 4, wrinkleFreq: 3, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.15 },
    physicalSize: { width: 120, height: 96, unit: 'in' },
    sizeLabel: '120×96" (304.8×243.8cm) Nursery Wall',
    productBase: { type: 'procedural', brightness: 240, shape: 'flat-surface' },
  },

  // ─── Gifting ───
  'wrapping-paper': {
    id: 'wrapping-paper',
    name: 'Wrapping Paper (Gift Box)',
    description: 'See your pattern on a wrapped gift box',
    category: 'gifting',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 8, height: 8, unit: 'in' },
    sizeLabel: '8×8" (20.3×20.3cm) Wrapping Paper (Gift Box)',
    productBase: { type: 'image', imagePath: '/mockups/wrapping_paper.png', maskPath: '/mockups/wrapping_paper_mask.png' },
    colorOverlay: { maskPath: '/mockups/wrapping_paper_bow_mask.png', defaultColor: 'auto' },
  },
  'gift-bag': {
    id: 'gift-bag',
    name: 'Gift Bag',
    description: 'Paper gift bag with pattern',
    category: 'gifting',
    canvasSize: { width: 700, height: 900 },
    patternArea: { x: 100, y: 100, width: 500, height: 650 },
    perspective: { topSqueeze: 25, bottomSqueeze: 0 },
    displacement: { intensity: 6, wrinkleFreq: 4, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 10, height: 13, unit: 'in' },
    sizeLabel: '10×13" (25.4×33cm) Gift Bag',
    productBase: { type: 'procedural', brightness: 230, shape: 'flat-surface' },
  },
  'wrapping-paper-v2': {
    id: 'wrapping-paper-v2',
    name: 'Wrapping Paper (Flat Sheet)',
    description: 'Wrapping paper sheet with gentle folds',
    category: 'gifting',
    canvasSize: { width: 900, height: 800 },
    patternArea: { x: 50, y: 50, width: 800, height: 700 },
    perspective: { topSqueeze: 12, bottomSqueeze: 0 },
    displacement: { intensity: 8, wrinkleFreq: 5, type: 'fabric-drape' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 30, height: 20, unit: 'in' },
    sizeLabel: '30×20" (76.2×50.8cm) Wrapping Paper (Flat Sheet)',
    productBase: { type: 'procedural', brightness: 240, shape: 'fabric-drape' },
  },

  // ─── Wallpaper ───
  'wallpaper': {
    id: 'wallpaper',
    name: 'Wallpaper',
    description: 'See your pattern as full-room wallpaper',
    category: 'wallpaper',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 86, height: 60, unit: 'in' },
    sizeLabel: '86×60" (218.4×152.4cm) Wallpaper',
    productBase: { type: 'image', imagePath: '/mockups/wallpaper.png', maskPath: '/mockups/wallpaper_mask.png' },
  },
  'wallpaper-roll': {
    id: 'wallpaper-roll',
    name: 'Wallpaper Roll',
    description: 'Wallpaper roll partially unrolled',
    category: 'wallpaper',
    canvasSize: { width: 700, height: 900 },
    patternArea: { x: 100, y: 50, width: 500, height: 800 },
    perspective: { topSqueeze: 15, bottomSqueeze: 5 },
    displacement: { intensity: 8, wrinkleFreq: 10, type: 'cylindrical' },
    blend: { mode: 'multiply', opacity: 0.88 },
    lighting: { enabled: true, intensity: 0.3 },
    physicalSize: { width: 20, height: 33, unit: 'in' },
    sizeLabel: '20×33" (50.8×83.8cm) Wallpaper Roll',
    productBase: { type: 'procedural', brightness: 235, shape: 'cylindrical' },
  },

  // ─── Stationery ───
  'journal': {
    id: 'journal',
    name: 'A5 Journal',
    description: 'See your pattern on an A5 journal cover',
    category: 'stationery',
    canvasSize: { width: 1024, height: 1024 },
    patternArea: { x: 0, y: 0, width: 1024, height: 1024 },
    perspective: { topSqueeze: 0, bottomSqueeze: 0 },
    displacement: { intensity: 0, wrinkleFreq: 0, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.9 },
    lighting: { enabled: true, intensity: 0.25 },
    physicalSize: { width: 5.5, height: 8.5, unit: 'in' },
    sizeLabel: '5.5×8.5" (14×21.6cm) A5 Journal',
    productBase: { type: 'image', imagePath: '/mockups/journal.png', maskPath: '/mockups/journal_mask.png' },
  },

  // ─── Accessories ───
  'silk-scarf': {
    id: 'silk-scarf',
    name: 'Silk Scarf',
    description: 'Flowing silk scarf with drape',
    category: 'accessories',
    canvasSize: { width: 800, height: 800 },
    patternArea: { x: 80, y: 80, width: 640, height: 640 },
    perspective: { topSqueeze: 20, bottomSqueeze: 15 },
    displacement: { intensity: 15, wrinkleFreq: 7, type: 'fabric-drape' },
    blend: { mode: 'multiply', opacity: 0.82 },
    lighting: { enabled: true, intensity: 0.35 },
    physicalSize: { width: 36, height: 36, unit: 'in' },
    sizeLabel: '36×36" (91.4×91.4cm) Silk Scarf',
    productBase: { type: 'procedural', brightness: 210, shape: 'fabric-drape' },
  },
  'phone-case': {
    id: 'phone-case',
    name: 'Phone Case',
    description: 'Smartphone case with slight curve',
    category: 'accessories',
    canvasSize: { width: 500, height: 900 },
    patternArea: { x: 60, y: 100, width: 380, height: 650 },
    perspective: { topSqueeze: 8, bottomSqueeze: 5 },
    displacement: { intensity: 5, wrinkleFreq: 12, type: 'radial-bulge' },
    blend: { mode: 'multiply', opacity: 0.90 },
    lighting: { enabled: true, intensity: 0.2 },
    physicalSize: { width: 3, height: 6, unit: 'in' },
    sizeLabel: '3×6" (7.6×15.2cm) Phone Case',
    productBase: { type: 'procedural', brightness: 225, shape: 'radial-bulge' },
  },
  'desk-mat': {
    id: 'desk-mat',
    name: 'Desk Mat',
    description: 'Large desk mat / mouse pad',
    category: 'accessories',
    canvasSize: { width: 1000, height: 500 },
    patternArea: { x: 50, y: 40, width: 900, height: 420 },
    perspective: { topSqueeze: 10, bottomSqueeze: 0 },
    displacement: { intensity: 3, wrinkleFreq: 4, type: 'flat-surface' },
    blend: { mode: 'multiply', opacity: 0.92 },
    lighting: { enabled: true, intensity: 0.15 },
    physicalSize: { width: 35, height: 16, unit: 'in' },
    sizeLabel: '35×16" (88.9×40.6cm) Desk Mat',
    productBase: { type: 'procedural', brightness: 60, shape: 'flat-surface' },
  },
};

export function getV2Template(id: string): MockupV2Template | undefined {
  return mockupV2Templates[id];
}

export function getAllV2Templates(): MockupV2Template[] {
  return Object.values(mockupV2Templates);
}

export function getV2TemplatesByCategory(category: string): MockupV2Template[] {
  return Object.values(mockupV2Templates).filter(t => t.category === category);
}

export function getAllV2Categories(): string[] {
  return [...new Set(Object.values(mockupV2Templates).map(t => t.category))];
}
